### ISSUE TITLE
Feature request: Environment Variable parameter section for AWS Shell Script task

### ISSUE THREAD

**Issue by sandor-juhasz** [aws/aws-toolkit-azure-devops#134]
Hi team,

The stock "Command Line Script" task has a very convenient parameter section called "Environment Variables" where env variables can be specified as name value pairs. This interface is very useful to pass secret variables to scripts as those need to be explicitly declared in the task otherwise they do not get passed. Would it be possible to add the same feature to the AWS Shell Script task?

Currently we use inline AWS Shell Scripts as workaround: we pass the secret variables in the "Arguments" parameter to a short inline script which sets up the environment variables and then calls the actual AWS shell script logic defined in another file. It works but it adds extra boilerplate to our pipeline definitions.

Thanks

**Comment by steveataws** [comment]
Sure, this should be easy to add. I don't have an ETA at this time though, especially with the holidays coming up!

**Comment by gopalramadugu** [comment]
@steveataws  This feature is really helpful if the script is big and provides better maintainability.  Do you have a time frame for this feature ?

**Comment by uright** [comment]
Is there a way as a work around even at this point for having environment variables to be entered into the task? Could this be passing in as parameters and then export as environment variables?

**Comment by hunterwerlla** [comment]
This has been released as part of 1.8.0
