### ISSUE TITLE
json files receive incorrect mime type of application/octet-stream

### ISSUE THREAD

**Issue by sbreakey** [aws/aws-toolkit-azure-devops#341]
**Is your feature request related to a problem? Please describe.**
We use the S3 deployment task to deploy a static website. In this site we have some json files. Because json is not in `knownMimeTypes` it gets `contentType = 'application/octet-stream'`. So we have to work around this various ways. Note that the existing override functionality (in advanced > Content Type) is global, for all files so does not solve the issue for us since there are images, html, css etc in the site.

**Describe the solution you'd like**
I guess the simplest fix would be to add `['.json', 'application/json'],` to knownMimeTypes in `Tasks/Common/s3.ts`. Not sure if there is a reason it isn't in there already though?
An additional option might be to do something as was done for the `Cache Control Expression` field so that we could have as much flexibility as possible, for example:
> */.json=application/json"

**Comment by michaelaplas** [comment]
Same issue here. I assume the mime type is missing?

**Comment by sbreakey** [comment]
I created a PR for this, but have just realized that perhaps this is deliberate since json text should be `application/json`, but jsonp should be `application/javascript`?

In which case I think the second proposal to allow the user to specify a custom content type, like they do with the cache control might be useful?

**Comment by hunterwerlla** [comment]
Yep that did seem to be missing, we should probably move to replace this list with a library or something more sophisticated than a 200 item list. Thanks for the Contribution!

**Comment by hunterwerlla** [comment]
Merged your PR and opened #343

**Comment by hunterwerlla** [comment]
This has been released as part of 1.8.0, thanks for the contribution!
