### ISSUE TITLE
s3 download task only downloads 999 files

### ISSUE THREAD

**Issue by Packet-Lost** [aws/aws-toolkit-azure-devops#346]
**Describe the bug**

The s3 download task seems to be limited to downloading 999 files when using a wildcard match. The task reports success without retrieving all items matched under the key prefix.

**To reproduce**

Upload over 1000 objects to an S3 bucket all using the same object key prefix. In our case this is our build output. We upload the objects using the S3 upload task and our object prefix contains the build number along with some branching information.
Use the s3 download task and configure the source folder to match the object prefix and use ** as the FileName Pattern.
In our case we output the downloaded s3 files to a windows file share on a separate system from the system running the VSTS task agent.
After the 999th file downloads the log reports:
Downloads from S3 completed
Finishing: S3 Download: (Task DisplayName)

**Expected behavior**

I would expect all files found in the s3 bucket matching the object key prefix to download.
If there is an expected limitation of 999 files and that limit is reached the task should fail.

**Your Environment**

-   cloud based with hosted build agents
-   Azure DevOps version: Cloud
-   AWS Toolkit for Azure DevOps version: 1.7.0

**Additional context**

I can provide more detailed logs and task output privately if it would help troubleshoot this issue.

**Comment by hunterwerlla** [comment]
That is very strange, the task is paginated: https://github.com/aws/aws-vsts-tools/blob/master/Tasks/S3Download/TaskOperations.ts#L99
We will have to look into this further

**Comment by hunterwerlla** [comment]
This has been released as part of 1.8.0
