### ISSUE TITLE
No task definition found.. in  CD

### ISSUE THREAD

**Issue by hbravoal** [aws/aws-toolkit-azure-devops#353]
I have a problem with the passage of my CD, the next mistake comes up: No task definition found matching ID 1b467810-6725-4b6d-accd-886174c09bba and version 0.156.11. You must register the task definition before uploading the package.
 It should be noted that it was from one moment to the next.

**Comment by hunterwerlla** [comment]
This is an unrelated task, see this issue here: https://github.com/microsoft/azure-pipelines-tasks/issues/13043
