### ISSUE TITLE
Option in ECR Push task to force repo name to conform to Docker specs

### ISSUE THREAD

**Issue by CherylFlowers** [aws/aws-toolkit-azure-devops#357]
**Is your feature request related to a problem? Please describe.**

I've been using the Azure Pipelines tasks to push images to the ACR. Now I'm working with the AWS toolkit to push to the ECR and I find that the push task is always failing because the repo name is not conforming to Docker repo name specs, specifically invalid upper case convention ie. My.Repo.Name

**Describe the solution you'd like**

A checkbox option in the ECR Push Image task to force the repo name to conform to Docker repo naming specs.

**Describe alternatives you've considered**

1. Manually rename the repo to conform to Docker specs. -- Simple? Yes. Easy to implement in a scenario with 100's (or 1000's) of repos? Hmm, perhaps not so much. It would be easier to allow devs to name a repo whatever they would like, and use the CD tools to sanitize it.
1. Add a pipeline task to modify the repo name before passing it to the ECR push task. -- There's a lot of really good posts in the SO community regarding this, and it would appear that some people have acheived some level of success with this approach. However, after 40+ revisions and still no successful push, I gave up. Gah.

**Additional context**

**Comment by hunterwerlla** [comment]
This has been released as part of 1.8.0, thanks for the contribution!
