### ISSUE TITLE
The specified module 'AWSPowerShell' was not loaded because no valid module file was found in any module directory.

### ISSUE THREAD

**Issue by manojkumaraut** [aws/aws-toolkit-azure-devops#376]
**Describe the bug**

Hi Team,

facing an issue in AWS Devops - AWS Powershell

Task Permissions
Permissions for this task to call AWS service APIs depend on the activities in the supplied script.
Checking install status for AWS Tools for Windows PowerShell module.

AWS Tools for Windows PowerShell module not found.
Installing AWS Tools for Windows PowerShell module to current user scope
                        
nuget                          2.8.5.208        https://onege... NuGet provider for the OneGet meta-package manager    

####[error]No match was found for the specified search criteria and module name 'AWSPowerShell'. Try Get-PSRepository to see all available registered module repositories.

##[error]The specified module 'AWSPowerShell' was not loaded because no valid module file was found in any module directory.

**To reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/9800500/97730696-36e42680-1afa-11eb-8ea6-87c724de4a3d.png)

**Your Environment**

-   On-prem or cloud based?:
-   Azure DevOps version:
-   AWS Toolkit for Azure DevOps version:

**Comment by hunterwerlla** [comment]
Powershell gallery has been having problems all day: https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md
