### ISSUE TITLE
Unable to deploy to Linux EB environment using the deploy Task

### ISSUE THREAD

**Issue by glacasa** [aws/aws-toolkit-azure-devops#393]
**Describe the bug**

I use Azure Devops to build my ASP .NET Core app and deploy it to Elastic Beanstalk.
When I try to deploy to a Linux instance, I get the following error :

    ERROR   Instance deployment: Your source bundle has a single .NET Core application. You must include a file with a '.runtimeconfig.json' suffix. The deployment failed.

I checked the package built, and the file is present.

When I deploy to a Windows instance, deployments is ok.

**To reproduce**

Create a new asp.net core project and save it in a Git repo in Azure Devops
Create a new Elastic Beanstalk environment «.NET Core on Linux»
Use the Azure Devops pipeline to build the ASP .NET Core app, and deploy it to Elastic Beanstalk using the «AWS Elastic Beanstalk Deploy Application» task.

Run the pipeline, and get the error message about missing '.runtimeconfig.json' file.

**Expected behavior**

I expect the app to be deployed on Elastic Beanstalk without error

**Your Environment**

-   Azure DevOps version: Cloud version
-   AWS Toolkit for Azure DevOps version: 1.9.0

**Additional context**

It seems that the Elastic Beanstalk Deploy task is building a package for Windows : it puts everything in a subfolder «app» and add a single file aws-windows-deployment-manifest.json at the root of the packate (saw this by downloading the package in AWS console)

This is made for Windows deployment, but Linux deployment expects the full app at the root of the zip file, so that's probably why I can't deploy to Linux.

I didn't find an option to deploy for Linux.

**Comment by hunterwerlla** [comment]
@glacasa Hello, what do you have your "Deployment Bundle Type" set to? There are several options:
<img width="401" alt="Screen Shot 2021-02-16 at 2 15 41 PM" src="https://user-images.githubusercontent.com/11964782/108128428-8fb3dc80-7061-11eb-82d9-1029d0d0c478.png">

**Comment by glacasa** [comment]
It is set to ASP.NET Core (Source: dotnet publish)

**Comment by hunterwerlla** [comment]
Ah, I see now. The label seems to be incorrect. It's specifically for windows, but we should add a Linux one and fix the label.

**Comment by bvulpes-seaworld** [comment]
Do we have a known workaround here? I would dearly like to not have to:
1. redo my Beanstalk environments with Windows servers
or...
2. reimplement the toolkit to upload just the zip file in question

Super curious to know what the recommended approach for deploying from ADO to EBS on Linux is.

**Comment by MatthewYork** [comment]
I was able to successfully work around it using the AWS CLI and uploading builds to a private S3 bucket. The pipeline has the following tasks:

...
<#your-build-tasks-before-publish#>
...

**Publish**
- **Arguments:** --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
- Uncheck "Zip published projects"

**Archive**
- **Root folder:** $(Build.ArtifactStagingDirectory)
- **Archive file to create:** $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip //or whatever you want to call it 

**S3 Upload**
- **Bucket Name:** create an s3 bucket and put it's name here. henceforth: <#your-bucket-name#>
- **Source Folder:** $(Build.ArtifactStagingDirectory)
- **filename patterns:** $(Build.BuildId).zip

**AWS CLI**
- **Command:** elasticbeanstalk
- **Subcommand:** create-application-version
- **Options and parameters:** --application-name <#your-app-name#> --version-label $(Build.BuildId) --description <#your-app-name#>-$(Build.BuildId) --source-bundle S3Bucket="<#your-bucket-name#>",S3Key="$(Build.BuildId).zip"

**AWS CLI**
- **Sommand:** elasticbeanstalk
- **Subcommand:** update-environment
- **Options and parameters:** --environment-name <#your-environment-name#> --version-label $(Build.BuildId)


### Comments
The main point of this is to pull the puslished web project (and generated *.runtimeconfig.json to the root of the deployment folder. This unifies the structure with that of the sample poject in AWS docs found [here](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/RelatedResources.html?icmpid=docs_elasticbeanstalk_console). Hope this helps!

**Comment by bvulpes-seaworld** [comment]
Winner winner, chicken dinner. Almost exactly where I landed, except with `Build.SourceVersion`. Thanks for following up, @MatthewYork .

**Comment by teo78** [comment]
Any schedule/plans for when this fix will be released?

**Comment by hunterwerlla** [comment]
This is part of today's 1.10 release

**Comment by glacasa** [comment]
Hi, thanks for this release.
I use it and now I can deploy to Linux EB environment 👍 

I just noticed that a file aws-windows-deployment-manifest.json is added to the bundle when I deploy to a Linux env.
It is empty and is probably not even read, so it's not a problem at all, but it is useless, maybe it shouldn't be added to the bundle

**Comment by Ace-Lightning** [comment]
I have the same issue on version `1.11.0`

Task definition:
```yaml
- task: BeanstalkDeployApplication@1
  inputs:
    awsCredentials: 'AWS connection for user ADBuild'
    regionName: '$(region_name)'
    applicationName: '$(application_name)'
    environmentName: '$(environment_name)'
    applicationType: 'aspnetCoreLinux'
    dotnetPublishPath: '$(Build.Repository.LocalPath)/out/'
    logRequest: true
    logResponse: true
```
