### ISSUE TITLE
Installed the version 1.9.0 for the extension in an Azure Devops and the tasks doesn't appear

### ISSUE THREAD

**Issue by lfraile** [aws/aws-toolkit-azure-devops#400]
Hello, I just installed the latest version (1.9.0) in an Azure DevOps Service account, and the service connection appears correctly but the tasks does not appears when configuring a pipeline.

I also checked in another Azure DevOps account, which was installed with older versions, but now are updated to 1.9.0 and the tasks appears correctly.

**To reproduce**

1. In an Azure DevOps service account, which has not installed previous versions of the extension, install the extension.
2. Go to create a pipeline, and from the tasks list, look for example to the S3 Download task, it does not appears.

**Expected behavior**

The task appears

**Screenshots**

**Your Environment**

-   Cloud Azure DevOps
-   AWS Toolkit for Azure DevOps version: 1.9.0, with no previous versions installed

**Additional context**
Looking at the repo I see this in the vss-extension.json:

``` json 
"files": [
        {
            "path": "images",
            "addressable": true
        },
        {
            "path": "Tasks/AWSCLI"
        },
        {
            "path": "Tasks/AWSPowerShellModuleScript"
        },
```

That *"Tasks/AWSPowerShellModuleScript"* folder seems incorrect from the perspective of your extension/repo organization, as it should be (according to your repo)  *"src/tasks/AWSPowerShellModuleScript"*

**Comment by hunterwerlla** [comment]
Hello, in general it takes a while for Azure DevOps to sync tasks (I have run into this issue while trying to test), running builds randomly seems to make it sync randomly.

As for paths, the repo has been reorganized several times, but we still build in the same way so those still work:
<img width="326" alt="Screen Shot 2021-03-22 at 9 04 36 AM" src="https://user-images.githubusercontent.com/11964782/112020565-b09ea000-8aed-11eb-993d-ac58af1b249a.png">

**Comment by lfraile** [comment]
Thanks @hunterwerlla everything ok now
