### ISSUE TITLE
AWS Powershell module takes a while to start

### ISSUE THREAD

**Issue by animusyosho** [aws/aws-toolkit-azure-devops#402]
**Is your feature request related to a problem? Please describe.**

My team wants deployments to be faster. One of the bottlenecks encountered is that it takes 2+ minutes for every instance of this task ("AWSPowerShellModuleScript") to spin up and "install AWS tools." 

**Describe the solution you'd like**

Perhaps some kind of caching, such as using the cache task provided by Micrososft: 
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops
https://www.epinova.no/en/folg-med/blog/2020/faster-build-pipeline-using-cache-task-in-azure-devops/
Maybe this could allow the AWS tools to be cached unless they have actually updated.

**Describe alternatives you've considered**

I'm struggling to find any way to speed this up myself as I don't control the contents of this task. However, if you have any suggestions I would be open to hearing them.

**Additional context**

**Comment by hunterwerlla** [comment]
Can you provide more details? The toolkit provides around 20 different tasks

**Comment by animusyosho** [comment]
Oh, sorry. The task I am specifically referring to is "AWSPowerShellModuleScript"

**Comment by animusyosho** [comment]
Fyi this was actually solved on the microsoft side. The awspowershell module should be preinstalled on windows build agents from now on. https://github.com/actions/virtual-environments/issues/5083
So this one can be closed as solved.
