### ISSUE TITLE
Service connection already exists

### ISSUE THREAD

**Issue by jeffreyjc911** [aws/aws-toolkit-azure-devops#403]
**Describe the bug**

I’m having both organization owner and project administrator roles. When I try to create a new service connection and it keeps showing the service connection already exists. However, I have filtered by keywords and there is no matched result, as highlighted in screenshot below. The result remains the same even if the extension been reenabled or reinstalled. 

**To reproduce**
1. Go to an Azure Project
2. Click on "Project Settings"
3. Click on "Service connections"
4. Click on "New service connection"
5. Select "AWS" and then next
6. Input the corresponding information and the desired service connection name, and then save

**Expected behavior**
The service connection can be created successfully and seen on the list. 

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/18098737/112248541-0e1f2200-8c91-11eb-92ca-66a849f08b29.jpg)

**Your Environment**

-   On-prem or cloud based?: Cloud based
-   Azure DevOps version: Dev18.M183.1 (AzureDevOps_M183_20210320.1)
-   AWS Toolkit for Azure DevOps version: 1.9.0

**Comment by hunterwerlla** [comment]
Hello, this seems to be an issue with permissions and/or Azure DevOps. We do not actively control this menu, we only specify that there is a service connection option with several fields.

**Comment by jeffreyjc911** [comment]
Thanks @hunterwerlla. This is surely not an issue with your program, as [the ticket](https://developercommunity.visualstudio.com/t/service-connection-already-exists/1375609) created on Microsoft Developer Community.
