### ISSUE TITLE
Updating AWS credentials messing up Service connection configuration

### ISSUE THREAD

**Issue by plantusd** [aws/aws-toolkit-azure-devops#407]
**Describe the bug**
The plugin seems to cache the AWS_SESSION_TOKEN, when setting up a new Service connection and filling 'Access Key ID', 'Secret Access Key', and 'Session Token (optional)' text fields with valid data - everything works fine, but when I'm updating this Service connection with a new valid 'Access Key ID' and 'Secret Access Key' (without 'Session Token (optional)') and running CI Pipeline again - the following error pops up 'Unable to resolve AWS account to use. It must be either configured when you define your CDK or through the environment'.
To verify whether AWS credentials are valid - I've created a new Service connection and filled it with AWS credentials without 'Session Token (optional)' - everything works fine (that's why I'm assuming caching issue)

**To reproduce**
1. Go to Project Settings 
2. Click on Service connections
3. Click on New service connection
4. Choose radio button w/ AWS logo
5. Click Next 
6. Fill up the following text fields: 'Access Key ID', 'Secret Access Key', 'Session Token (optional)' w/ valid AWS credentials
7. Click Save 
8. Run CI Pipeline which is using created previously Service connection to ensure everything is ok
9. Update Service connection w/ new 'Access Key ID' and 'Secret Access Key' (leave 'Session Token (optional)' empty)
10. Run CI Pipeline - at this step I'm facing the error

**Expected behavior**
Updating Service connection with valid AWS credentials doesn't break CI Pipeline

**Your Environment**
-   On-prem or cloud based?: Cloud
-   Azure DevOps version:
-   AWS Toolkit for Azure DevOps version: 1.9.0

**Additional context**
We're using AWS CDK w/ the plugin and
I'm aware that AWS Toolkit for Azure DevOps doesn't support AWS CDK currently - but I don't think this affects the issue, since we're using inlineScript only

**Comment by hunterwerlla** [comment]
Hello, based on the text of the bug report this seems like an issue with Azure DevOps itself. We do not cache credentials anywhere and have very little control over the UI.

**Comment by bryceitoc9** [comment]
Closing this issue since it seems like there's no further action. Feel free to reopen if you're still seeing issues!
