### ISSUE TITLE
Can I update Secret Access Key in service connection via API?

### ISSUE THREAD

**Issue by aaronzhao-com** [aws/aws-toolkit-azure-devops#418]
Hi, We want to automate AWS Secret Access Key rotation for Azure DevOps service connection. Is there any API we can use to update it?

**Comment by bryceitoc9** [comment]
Hi @aaronzhao-com , apologies for the delay. If you have access to the build host, you could set credentials programmatically by using environment variables: https://docs.aws.amazon.com/vsts/latest/userguide/getting-started.html#credentials-standard-aws-env-variables ; additionally, if you're using an EC2 instance, you can use the instance's Instance Profile: https://docs.aws.amazon.com/vsts/latest/userguide/getting-started.html#credentials-ec2-build-agents .

Hope this helps!
