### ISSUE TITLE
Update AWS CLI version to support AWS Proton CMDs

### ISSUE THREAD

**Issue by almadiso** [aws/aws-toolkit-azure-devops#431]
**Is your feature request related to a problem? Please describe.**

Current version of AWS CLI that gets installed by the toolkit does not support Proton AWS CLI commands. 
AWS CLI v2.1.29 is included in the aws-toolkit-azure-devops version is v1.11.0

**Describe the solution you'd like**

Update the Toolkit to install AWS CLI v2.2.11 or greater

**Describe alternatives you've considered**

Update AWS CLI version manually on Build Servers

**Additional context**

**Comment by bryceitoc9** [comment]
Hi @almadiso 

Apologies for the late response here, but the toolkit doesn't install the CLI automatically. If you host your own pipelines agents, you can install the updated CLI directly on them; if you're using Azure-hosted agents, you'll want to install the CLI inline as part of the job (Pip or Chocolatey should work).

Let us know if you have any other questions!
