### ISSUE TITLE
Failed to obtain authorization token to log in to ECR

### ISSUE THREAD

**Issue by EricKao** [aws/aws-toolkit-azure-devops#483]
**Describe the bug**
When we use AWS Toolkit on Azure DevOps, we would like to push a docker image to AWS ECR, for some reason, it's always show below error messages, and we can't continue running the reset of automation process, we've confirmed the service connection is set correctly and the ECRPushImage version is 1.3.

##[error]Error: Failed to obtain authorization token to log in to ECR, error: CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

**To reproduce**
1. Create a new service connection of type AWS, and fill in related ECR credientials.
2. Use AWS ECR Push task in the pipeline YAML file.
3. Each time when running push docker image part, it will show failed to obtain authorization token to log in to ECR.

**Expected behavior**

It should get authorization successfully and push docker image to the ECR.

**Your Environment**

-   On-prem or cloud based?: Cloud
-   Azure DevOps version: 
-   AWS Toolkit for Azure DevOps version: 1.13.0

**Comment by EricKao** [comment]
Fixed this issue by setting the correct permission role on AWS, close this issue.

**Comment by amantcs** [comment]
@EricKao What permissions you added? I am also getting the same issue in a particular region only.

**Comment by rowanfreeman-acutro** [comment]
> @EricKao What permissions you added? I am also getting the same issue in a particular region only.

This solution worked for me when it's region-specific: https://github.com/aws/aws-toolkit-azure-devops/issues/547#issuecomment-2002664946
