### ISSUE TITLE
Does node16 need to be added "Node runner update guidance for Azure Pipelines task authors"?

### ISSUE THREAD

**Issue by hansterwal** [aws/aws-toolkit-azure-devops#548]
Hi,

First of this is more of a question than a bug.

Our concern is that tasks will start to fail when the support for the node10 runner is dropped as with the node 6 runner prior which was fixed with version [1.1.3.0](https://github.com/aws/aws-toolkit-azure-devops/issues/453) . Microsoft released the following call to action last year:

>To ensure tasks that use a Node runner remain working on the Azure Pipelines agent, task authors need to update Node dependent tasks to use the Node 16 runner.

>As Microsoft Hosted agents and various Azure DevOps Server versions have different lifecycles, there can be different Node runner versions installed depending on where a task is running. To be able to run the same task on agents with different Node runner versions, task.json can contain [multiple execution sections](https://github.com/microsoft/azure-pipelines-tasks/blob/master/docs/migrateNode16.md#upgrading-tasks-to-node-16):

 >Copy
````json
 "execution": {
    "Node10": {
      "target": "bash.js",
      "argumentFormat": ""
    },
    "Node16": {
      "target": "bash.js",
      "argumentFormat": ""
    }
````
>In the above example, Azure Pipeline agents which include the Node 16 runner will choose it by default, and those which don’t will fall back to the Node 10 implementation."

[Reference to call to action](https://devblogs.microsoft.com/devops/node-runner-update-guidance-for-azure-pipelines-task-authors/)

Is this something to be worried about?

**Comment by yaunj** [comment]
Just had this issue with the azure-pipelines-agent v3.238.0.

> ##[error]This step requires a node version that does not exist in the agent filesystem. Path: /opt/azure-pipelines-agent/externals/node10/bin/node

The failing task was `AWSShellScript@1`

**Comment by yaunj** [comment]
I did some more checking, and for now, node10 is only removed from the "Alternate Agent Downloads" [release for 3.238.0](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v3.238.0) (pipelines-agent, not vsts-agent), so currently it's only affecting users who chose the pipelines agent over the vsts agent to avoid running node6.

**Comment by rbbarad** [comment]
@hansterwal @yaunj thanks for bringing this to our attention. I'm taking a look into this + #551. Will update with more details as they come.

**Comment by yaunj** [comment]
Any update on this @rbbarad?

**Comment by rbbarad** [comment]
Approved the PR. Aiming to release this next week. Thanks for your contribution!

**Comment by rbbarad** [comment]
Supporting Node 16 migration requires updating `azure-pipelines-task-lib` dependency (see https://github.com/aws/aws-toolkit-azure-devops/pull/560). We are currently blocked from doing this due to an issue with bundling `azure-pipelines-task-lib`'s `shelljs` dependency (see description in https://github.com/aws/aws-toolkit-azure-devops/pull/539 for more details). 

We've temporarily reverted PR #551 (https://github.com/aws/aws-toolkit-azure-devops/pull/560) as we investigate a workaround for this issue.

**Comment by stefanfreitag** [comment]
Good evening  @rbbarad,
Any update on the status of your investigation? Any help needed?

**Comment by bfeliano** [comment]
Pipelines are now throwing warnings due to node version

```
##[warning]Task 'AWS CLI' version 1 (AWSCLI@1) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

##[warning]Task 'AWS Shell Script' version 1 (AWSShellScript@1) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance
```

**Comment by sameerahmed720** [comment]
same here , even after updating AWSCLI1 to 2 , issue is still arising 
@rbbarad any suggestions

**Comment by justinmk3** [comment]
https://github.com/aws/aws-toolkit-azure-devops/pull/581
