### ISSUE TITLE
Receiving warning regarding Node version with S3Upload task

### ISSUE THREAD

**Issue by danspam** [aws/aws-toolkit-azure-devops#575]
**Describe the bug**

We are receiving a warning in Azure Dev Ops regarding the version of node S3Upload task is using:

Task 'Amazon S3 Upload' version 1 (S3Upload@1) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

**To reproduce**

Run an S3Upload@1 task in Azure DevOps Cloud

**Expected behavior**

Task should not produce warnings

**Your Environment**

Azure DevOps cloud

**Comment by martinculen** [comment]
This is already tracked here: https://github.com/aws/aws-toolkit-azure-devops/issues/566
