### ISSUE TITLE
Node version(10) is no longer supported for AWS toolkit

### ISSUE THREAD

**Issue by nithinkolli17** [aws/aws-toolkit-azure-devops#578]
Node version(10) is no longer supported for AWS toolkit ?. This is causing warning on Azure Devops pipeline build process

##[warning]Task 'AWS Shell Script' version 1 (AWSShellScript@1) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

Anyone facing the same ?

**Comment by chillistar** [comment]
Yes, started happening a few weeks ago (or I noticed it then). Looks like there is no version 2 to switch to yet.

**Comment by justinmk3** [comment]
See https://github.com/aws/aws-toolkit-azure-devops/issues/566

**Comment by madhan987** [comment]
Hi, We are using **AWSShellScript@1** in our pipeline's, could you let us know any alternative solution or when will be the node update for **AWSShellScript@1**

**Comment by ajith-shan-m** [comment]
Hey guys ( @nithinkolli17  , @chillistar , @justinmk3 , @madhan987 ) 
anyone got a solution for this ?

**Comment by juanosog11** [comment]
Hello people, even if the update was uploaded to node 20, the alert still appears in Azure Devops

##[warning]Task 'AWS Shell Script' version 1 (AWSShellScript@1) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

my pipelines are in version 20 of node

**Comment by hayemaxi** [comment]
> See #566
