### ISSUE TITLE
Node Lambda Integration Needs to Save Configuration

### ISSUE THREAD

**Issue by ddrinka** [aws/aws-toolkit-azure-devops#76]
When deploying a .Net Lambda function the tool saves the configuration and will deploy with an identical configuration the next time.  The Node.JS Lambda integration does not support saving the configuration, requiring me to re-enter all parameters for each deploy.

Please add similar configuration saving functionality to the Node.JS deployment functionality.

**Comment by steveataws** [comment]
Based on your other issue, I assume we are talking about the Publish to AWS Lambda wizard in the Visual Studio toolkit, not the Team Services integration tools.

The ability to save the deployment configuration is currently specific to .NET tooling (VS and the dotnet CLI extensions). The ability to publish Node.js functions is quite old and to now we've had no plans to extend it. We will at least take a look so see if this is a simple enhancement we can backport but I've no ETA I can offer.
